<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE suite SYSTEM "http://testng.org/testng-1.0.dtd">
<suite thread-count="15" name="Failed suite [Suite]" parallel="tests">
  <test name="Test4(failed)" parallel="tests">
    <classes>
      <class name="com.salesforce.TestCases.CreateProjectTest">
        <methods>
          <include name="setup"/>
          <include name="setup"/>
          <include name="setup"/>
          <include name="setup"/>
          <include name="setup"/>
          <include name="setup"/>
          <include name="setup"/>
          <include name="setup"/>
          <include name="setup"/>
          <include name="setup"/>
          <include name="breakdown"/>
          <include name="breakdown"/>
          <include name="breakdown"/>
          <include name="breakdown"/>
          <include name="breakdown"/>
          <include name="breakdown"/>
          <include name="breakdown"/>
          <include name="breakdown"/>
          <include name="breakdown"/>
          <include name="breakdown"/>
          <include name="chec"/>
          <include name="done"/>
          <include name="testCreateFolder"/>
        </methods>
      </class> <!-- com.salesforce.TestCases.CreateProjectTest -->
    </classes>
  </test> <!-- Test4(failed) -->
</suite> <!-- Failed suite [Suite] -->
